HackNIEC/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('onlinetest.urls')),
]

onlinetest/urls.py
from django.conf.urls import url
from HackNIEC import settings
from . import views
from django.conf.urls.static import static


app_name = 'onlinetest' 
#This sets application namespace to diffretiate urls of different apps.

urlpatterns = [
    #url for home-page:
    url(r'^$', views.index, name='index'),
    url(r'^index$', views.index, name='index'),
    
    #url for login-page:
    url(r'^clientlogin$', views.clientlogin, name='clientlogin'),
    #url for signup-page:
    url(r'^clientregister$', views.clientregister, name='clientregister'),
    url(r'^addidea$', views.addidea, name='addidea'),
    url(r'^submitidea$', views.submitidea, name='submitidea'),
    url(r'^viewidea$', views.viewidea, name='viewidea'),
    url(r'^submitfeedback$', views.submitfeedback, name='submitfeedback'),
    url(r'^feedback$', views.feedback, name='feedback'),
    url(r'^clientadmin$', views.clientadmin, name='clientadmin'),
    url(r'^clientloginval$', views.clientloginval, name='clientloginval'),
    url(r'^clientlogout', views.clientlogout, name='clientlogout'),
    url(r'^register$',views.register, name='register'),
    url(r'^studentmarksdisplay$',views.studentmarksdisplay, name='studentmarksdisplay'),

    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinetest/models.py
from django.db import models
from django.utils import timezone


class Users(models.Model):
    first_name = models.CharField(max_length=30)
    email = models.CharField(max_length=120, unique=True)
    pwd= models.CharField(max_length=80)
    #no_of_topics=models.IntegerField(default=0)
    #type_user=models.IntegerField(default=0) #simple=0 org=1
    def __str__(self):
        return self.email

class Idea(models.Model):
    """ideas """
    title = models.CharField(max_length=300, unique=True)
    description = models.EmailField(max_length=1200)
    link = models.CharField(max_length=500, default=None)
    prototype_link = models.CharField(max_length=500, default=None)
    user = models.CharField(max_length=50)
    tag = models.CharField(max_length=50)
    public = models.CharField(max_length=5)
    
    def __str__(self):
        return self.title

class Feedback(models.Model):
    title = models.CharField(max_length=300)
    feedback = models.CharField(max_length=600)
    user = models.CharField(max_length=50)
    feedback_id = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.feedback_id

onlinetest/forms.py
import datetime
from django import forms


class SignupForm(forms.Form):
    firstname = forms.CharField(max_length=30)
    email = forms.CharField(max_length=120)
    pwd= forms.CharField(max_length=80)

class LoginForm(forms.Form):
    email=forms.CharField(max_length = 80)
    pwd= forms.CharField(max_length=80)

class IdeaForm(forms.Form):
    title = forms.CharField(max_length=200)
    description = forms.CharField(max_length=1000)
    link = forms.CharField(max_length=400)
    prototype_link = forms.CharField(max_length=400)
    public = forms.CharField(max_length=20)
    tag = forms.CharField(max_length=40)

"""
class AddTopicForm(forms.Form):
    topic_text=forms.CharField(max_length = 250)
    topic_desc=forms.CharField(max_length = 700)
    tag_text=forms.CharField(max_length = 250)

class AddOpinionForm(forms.Form):
    opinion_text=forms.CharField(max_length = 500)
    topic = forms.CharField(max_length = 5)
"""


class SearchForm(forms.Form):
    topic_text=forms.CharField(max_length = 250)
    #symptom=forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,required=False)


class TestIdVal(forms.Form):
    test_id=forms.CharField(max_length = 250)

onlinetest/views.py
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist  # This may be used instead of Users.DoesNotExist
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from .forms import LoginForm, SignupForm, IdeaForm, SearchForm
# for older versoins of Django use:
# from django.core.urlresolvers import reverse
import ast
from .models import Users, Idea, Feedback
from django.utils.timezone import datetime

import random
#from Crypto.cipher import AES

# from main.forms import SignupForm,LoginForm,SearchForm#,AddTopicForm,AddOpinionForm,

marks = 0
ques_no = 0
questions = []

def index(request):
    return render(request, 'onlinetest/index.html')


def clientlogin(request):
    return render(request, 'onlinetest/clientlogin.html')

def clientregister(request):
    return render(request, 'onlinetest/clientregister.html')

def clientadmin(request):
    if request.session.has_key('user_id'):
        uid = request.session['user_id']
        try:
            user = Users.objects.get(pk=uid)
            return render(request, 'onlinetest/clientadmin.html', {'user_id': user})
        except Users.DoesNotExist:
            return render(request, 'onlinetest/clientlogin.html')
        except quesFile.DoesNotExist:
            return render(request, 'onlinetest/clientadmin.html')
    else:
        return render(request, 'onlinetest/clientlogin.html')

def addidea(request):
    if request.session.has_key('user_id'):
        uid = request.session['user_id']
        try:
            user = Users.objects.get(pk=uid)
            return render(request, 'onlinetest/addidea.html', {'user_id': user})
        except Users.DoesNotExist:
            return render(request, 'onlinetest/clientlogin.html')
        
    else:
        return render(request, 'onlinetest/clientlogin.html')

def submitidea(request):
    if request.session.has_key('user_id'):
        uid = request.session['user_id']
        #return HttpResponse('1 ' + request.POST.get('title') + '2 ' + request.POST.get('description') + '3 ' + request.POST.get('link') + '4 ' + request.POST.get('prototype_link') + '5 ' + request.POST.get('tag'))
        if request.method == 'POST':
            idea = IdeaForm(request.POST)
        if idea.is_valid():
            user = Users.objects.get(id=uid)
            if idea.cleaned_data.get('public').lower() == 'no':
                sta = 0
            else:
                sta = 1
            p = Idea(
                title=idea.cleaned_data.get('title'),
                description=idea.cleaned_data.get('description'),
                link=idea.cleaned_data.get('link'),
                prototype_link=idea.cleaned_data.get('prototype_link'),
                user=user,
                tag=idea.cleaned_data.get('tag'),
                public=str(sta),
            )
            p.save()
        else:
            return HttpResponse("error")    
        return HttpResponseRedirect(reverse('onlinetest:clientadmin'))
    else:
        return render(request, 'onlinetest/clientlogin.html')

def feedback(request):
    tabledata = Feedback.objects.filter()
    return render(request, 'onlinetest/feedback.html', {'tabledata': tabledata})


def viewidea(request):
    if request.session.has_key('user_id'):
        uid = request.session['user_id']
        if request.method != 'POST' and request.POST.get('my') == None:
            user=Users.objects.get(id=uid)
            tabledata = Idea.objects.filter(public='1')
            #return HttpResponse(str(user) + tabledata[0].user)
            return render(request, 'onlinetest/viewidea.html', {'tabledata': tabledata, 'user': str(user)})
        elif request.method == 'POST' and request.POST.get('my') != None:
            user=Users.objects.get(id=uid)
            tabledata = Idea.objects.filter(user=user)
            return render(request, 'onlinetest/viewidea.html', {'tabledata': tabledata, 'user': str(user)})
            return HttpResponse(tabledata)
        else:
            
            tabledata = Idea.objects.filter()
            #return HttpResponse(data.user)
            return render(request, 'onlinetest/viewidea.html', {'tabledata': tabledata})
    else:
        return render(request, 'onlinetest/clientlogin.html')

def submitfeedback(request):
    if request.session.has_key('user_id'):
        uid = request.session['user_id']
        
        if request.method == 'POST' and request.POST.get('feedback') != None:
            user=Users.objects.get(id=uid)
            now = str(datetime.now().strftime("%Y%m%d%H%M"))
            #return HttpResponse(str(datetime.now().strftime("%Y%m%d%H%M")) + str(user))
            p = Feedback(
                title=request.POST.get('title'),
                feedback=request.POST.get('feedback'),
                user=user,
                feedback_id=now,
                
            )
            p.save()
            tabledata = Idea.objects.filter(public='1')
            #return HttpResponse(data.user)
            return HttpResponseRedirect(reverse('onlinetest:viewidea'))
            return render(request, 'onlinetest/viewidea.html', {'tabledata': tabledata})
    else:
        return render(request, 'onlinetest/clientlogin.html')

def clientloginval(request):
    if request.method == 'POST':
        log = LoginForm(request.POST)
        if log.is_valid():
            try:
                user = Users.objects.get(email=log.cleaned_data.get('email'), pwd=log.cleaned_data.get('pwd'))
                request.session['user_id'] = user.id
                useremail = user.email
                return HttpResponseRedirect(reverse('onlinetest:clientadmin'))
            except Users.DoesNotExist:
                return HttpResponse("Wrong Username Password")


def clientlogout(request):
    try:
        del request.session['user_id']
        return HttpResponseRedirect(reverse('onlinetest:index'))
    except:
        pass
    return HttpResponseRedirect(reverse('onlinetest:index'))


def register(request):
    if request.method == 'POST':
        signup = SignupForm(request.POST)
        if signup.is_valid():
            p = Users(
                first_name=signup.cleaned_data.get('firstname'),
                email=signup.cleaned_data.get('email'),
                pwd=signup.cleaned_data.get('pwd'),
            )
            p.save()
            request.session['user_id'] = p.id
    return HttpResponseRedirect(reverse('onlinetest:clientadmin'))




def simple_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        now = str(datetime.now().strftime("%Y%m%d%H%M"))
        ques_paper = quesFile.objects.create(ques_paper_id=now, client=str(request.session['user_id']))
        ques_paper.save()
        myfile = request.FILES['myfile']
        ext = myfile.name[myfile.name.rfind('.'):]
        fs = FileSystemStorage()
        filename = fs.save(now + ext, myfile)
        onlinetest.file_reader.file_to_db(filename, str(request.session['user_id']), now)
# return HttpResponse("now" + filename + "request.session['user_id']" + str(request.session['user_id']))
        uploaded_file_url = fs.url(filename)
        return render(request, 'onlinetest/clientadmin.html', {
            'uploaded_file_url': uploaded_file_url,
        })
    return render(request, 'onlinetest/clientadmin.html')


def studentmarksdisplay(request):
    sinfo = studentProfile.objects.all()
    smarks = studentMark.objects.all()
    return render(request, 'onlinetest/studentmarks.html', {'smarks': smarks, 'sinfo':sinfo})

onlinetest/templates/onlinetest/addidea.html
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600italic,700,800'
          rel='stylesheet'
          type='text/css'>
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans">
    <link href='https://fonts.googleapis.com/css?family=Sonsie+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'onlinetest/css/style1.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'onlinetest/css/imagehover.min.css' %}" type="text/css"/>
    <style>
        .custab {
            border: 1px solid #ccc;
            padding: 5px;
            margin: 5% 0;
            box-shadow: 3px 3px 2px #ccc;
            transition: 0.5s;
        }

        .custab:hover {
            box-shadow: 3px 3px 0px transparent;
            transition: 0.5s;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html"><span>hack</span>IDEA</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/">Home</a></li>
                <li><a href="/">About</a></li>

                <li class="btn-trial"><a href="/">It's Free </a></li>
            </ul>
        </div>
    </div>
</nav>
<br>
<br><br>
<br>
<div class="container">

    <a href="../clientlogout" class="btn btn-success btn-lg" style="float: right">Logout</a>
    <p>
    </p>
</div>
<br/>
<form class="form col-md-12 center-block" method="POST" action="{% url 'onlinetest:submitidea' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control input-lg" name="title" placeholder="title" required>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control input-lg" name="description" placeholder="Description starts here....">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control input-lg" name="link" placeholder="link of presentation, pdf, etc (optional)">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control input-lg" name="prototype_link" placeholder="link of your prototype (optional)">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control input-lg" name="tag" placeholder="Add Tags">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control input-lg" name="public" placeholder="public or not">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-lg btn-block">ADD IT</button>
                        
                    </div>
                </form>
<br>
            <br><br>
            <br><br>
            <br><br>
            <br><br>
            <br>
<center>
    <footer id="footer" class="footer">
        <br> ©2017 Open Source. All rights exploited
        <div class="credits">
            Designed and Developed for <a href="/"><b> HackIDEA</b></a><br>
            <br>
            <br>
        </div>
        </div>
    </footer>
</center>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" Async></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" Async
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

</body>

</html>

onlinetest/templates/onlinetest/clientlogin.html
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600italic,700,800' rel='stylesheet'
        type='text/css'>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans">
    <link href='https://fonts.googleapis.com/css?family=Sonsie+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'onlinetest/css/style1.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'onlinetest/css/imagehover.min.css' %}" type="text/css" />
</head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
                <a class="navbar-brand" href="index.html"><span>Hack</span>Idea</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/">Home</a></li>
                    <li><a href="/">About</a></li>
                    
                    <li class="btn-trial"><a href="/">It's Free  </a></li>
                </ul>
            </div>
        </div>
    </nav>
    <br>
    <br><br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <center>
                    <h3>Sign IN</h3>
                </center><br>
                <form class="form col-md-12 center-block" method="POST" action="{% url 'onlinetest:clientloginval' %}">
                    {% csrf_token %}
                    <center>
                        <input type="text" class="form-control input-lg" name="email" placeholder="Email" required>
                        <br>
                        <input type="password" class="form-control input-lg" name="pwd" placeholder="Password" required>
                    </center>
                    <br>
                    <button class="abcbut" type="submit">Login</button> <center>or 
                    <a href="/clientregister" class="abcbut">Signup</a></center>
                </form>
            </div>
        </div>
    </div>
    <br>

    <br>
    <center>
        <footer id="footer" class="footer">
            <br> ©2017 Open Source. All rights exploited
            <div class="credits">
                Designed and Developed for <a href="/"><b> HackIDEA</b></a><br>
                <br>
                <br>
            </div>
            </div>
        </footer>
    </center>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" Async></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" Async integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

</body>

</html>

onlinetest/templates/onlinetest/clientregister.html
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600italic,700,800' rel='stylesheet'
        type='text/css'>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans">
    <link href='https://fonts.googleapis.com/css?family=Sonsie+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'onlinetest/css/style1.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'onlinetest/css/imagehover.min.css' %}" type="text/css" />
</head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
                <a class="navbar-brand" href="index.html">Hack<span>IDEA</span></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/">Home</a></li>
                    <li><a href="/">About</a></li>

                    <li class="btn-trial"><a href="/">It's Free  </a></li>
                </ul>
            </div>
        </div>
    </nav>
    <br>
    <br><br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <center>
                    <h3>Register</h3>
                </center><br>
                <form class="form col-md-12 center-block" method="POST" action="{% url 'onlinetest:register' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control input-lg" name="firstname" placeholder="First-Name" required>
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control input-lg" name="email" placeholder="Email-ID" required>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control input-lg" name="pwd" placeholder="Password" required>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control input-lg" name="cpwd" placeholder="Confirm-Password" required>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-lg btn-block">Sign Up</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
     <br>

    <br>
    <center>
        <footer id="footer" class="footer">
            <br> ©2017 Open Source. All rights exploited
            <div class="credits">
                Designed and Developed for <a href="/"><b> HackIDEA</b></a><br>
                <br>
                <br>
            </div>
            </div>
        </footer>
    </center>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" Async></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" Async integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

</body>

</html>

onlinetest/templates/onlinetest/viewidea.html
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600italic,700,800'
          rel='stylesheet'
          type='text/css'>
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans">
    <link href='https://fonts.googleapis.com/css?family=Sonsie+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'onlinetest/css/style1.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'onlinetest/css/imagehover.min.css' %}" type="text/css"/>
    <style>
        .custab {
            border: 1px solid #ccc;
            padding: 5px;
            margin: 5% 0;
            box-shadow: 3px 3px 2px #ccc;
            transition: 0.5s;
        }

        .custab:hover {
            box-shadow: 3px 3px 0px transparent;
            transition: 0.5s;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html"><span>hack</span>IDEA</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/">Home</a></li>
                <li><a href="/">About</a></li>

                <li class="btn-trial"><a href="/">It's Free </a></li>
            </ul>
        </div>
    </div>
</nav>
<br>
<br><br>
<br>
<div class="container">

    <a href="../clientlogout" class="btn btn-success btn-lg" style="float: right">Logout</a>
    <p>
    </p>
</div>
<br/>
<form class="form col-md-12 center-block" method="POST" action="{% url 'onlinetest:viewidea' %}">
<center><input type="submit" class="btn btn-danger" value="View My IDEAS"></center>
<input type="text" value="1" name="my" hidden>
<br>
{% csrf_token %}
</form>            
<center>
    <div class="custyle" style="width: 70%;align-content: center">
        <table class="table table-striped custab">
            <thead>
            <tr>
                <th>Idea</th>
                <th>Description</th>
                <th>Link</th>
                <th>Prototype Link</th>
                <th>Tags</th>
                <th>User</th>
            </tr>
            </thead>
            <tbody>
            {% for tabledata in tabledata %}
                <tr>
                    <td>{{ tabledata.title }}</td>
                    <td>{{ tabledata.description }}</td>
                    <td><a href="{{ tabledata.link }}">{{ tabledata.link }}</a></td>
                    <td><a href="https://{{ tabledata.prototype_link }}">{{ tabledata.prototype_link }}</a></td>
                    <td>{{ tabledata.tag }}</td>
                    <td>{{ tabledata.user }}</td>
                    <td>
                        {% if user == tabledata.user %} 

                            <button  class="btn btn-danger" onclick='var google_q = "{{ tabledata.tag }}";
    var angelco_q = "{{ tabledata.tag }}";
    var google_str = google_q.replace(",", "+");
    var angelco_str = yoyo(angelco_q);yeye(google_str, angelco_str);'>Validate Idea</button>`
                        {% else %}
                            <form class="form col-md-12 center-block" method="POST" action="{% url 'onlinetest:submitfeedback' %}">
                            <center><input type="text" name="feedback" placeholder="give feedback"></center>
                            <center><input type="submit" class="btn btn-danger" value="post"></center>
                               <input type="text" name="title" value="{{ tabledata.title }}" hidden>
                            <input type="text" value="1" hidden>
                            <br>
                            {% csrf_token %}
                            </form>            
                            
                        {% endif %}
                    </td>
                </tr>
                
            {% endfor %}
            </tbody>
        </table>
    </div>
</center>


<center>
    <footer id="footer" class="footer">
        <br> ©2017 Open Source. All rights exploited
        <div class="credits">
            Designed and Developed for <a href="/"><b> HackIDEA</b></a><br>
            <br>
            <br>
        </div>
        </div>
    </footer>
</center>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" Async></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" Async
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

<script>

function yeye(google_str, angelco_str)
{ 
    window.open('https://www.google.co.in/#q=startups+related+to+' + google_str,'','width=700,height=700'); 
    window.open('https://angel.co/companies?keywords[]=' + angelco_str,'','width=700,height=700');
}
function yoyo(stri)
{


return stri.replace(",", "&keywords[]=");
}
</script>

</body>

</html>